### PR TITLE
Add /metrics endpoint exporting prometheus metrics

### PR DESCRIPTION
**Pull request by yleong**
Hi @kaihendry , I am now monitoring my own instance using Prometheus. I am opening this PR in case you'd find it useful. Otherwise please feel free to close and I'll maintain my own fork. 

The /metrics endpoint will allow for monitoring the rate and response code of LTA API calls.

### CODE REVIEW

**Comment by kaihendry** [comment]
This is interesting. You run your own copy just to monitor the LTA API?

Really have no idea it was so easy to monitor at API with promauto. Guess I should give it a try.

I also wanted to measure unique users, this is why I have set a cookie lately. Any good solutions for that from the prom world?

Also nice to meet another Prom user. I thought it might be the only one in Singapore. ;)

**Comment by yleong** [comment]
I run a copy at `bus.sigsegv.run` just for fun. I have added another commit to create a `unique_visitors` counter. It leverages the existing cookie code.

**Comment by kaihendry** [comment]
iiuc you're tracking or fingerprinting with UA string, right? Not **visitorID** as I am trying.

Anyway after thinking about it, I don't think it makes sense to instrument this using prom since I run this from a lambda environment where the process can be killed and the counter maligned between scrapes.

I plan to count visitors by [computing my CloudWatch logs](https://s.natalian.org/2019-01-10/1547131668_2548x1398.png). Another idea if for the clients to maintain a counter in their cookie hashed with my secret so they can tell me how much they use the site. ;) 

How do you run copy on `bus.sigsegv.run`? Behind Cloudflare somewhere to your own box?

Nonetheless, I am going to ask _you_ questions on future about prom instrumenting. Can you think of ways to improve https://github.com/unee-t/dbcheck ? ;)

**Comment by yleong** [comment]
Using visitorID as a label is of course possible, but I wasn't comfortable with implementing granular tracking. 

You are right that the counter will reset. The cookie idea sounds more reliable than wrangling logs.

I am running it from a spare t430s with an Argo Tunnel to the Cloudflare edge, because you never know when somebody in Lagos needs to know the bus timings in Sembawang ;-) 

re: dbcheck,  your question is too broad and I have no context into its purpose. I am no Prometheus expert, but if you have a specific question, we might explore that together.

**Comment by kaihendry** [comment]
Would be cool to measure the performance of the LTA API. I just added a measurement in my logs. I need to probably refactor it further so it can be plotted over time.

Anyway, just to reminder I won't be incorporating prom stuff since this is usually run in a short lived serverless environment!

**Pull request closed without merging**
